### ISSUE TITLE
Error in sort_elements funtion in febio_scene.py 

### ISSUE THREAD

**Issue by Ziemnono** [mimesis-inria/caribou#130]
Since a bump of my NumPy and meshio version I have the following error:
```
[ERROR]   [SofaRuntime] TypeError: cannot unpack non-iterable CellBlock object
Traceback (most recent call last):
  File "febio_rectangular_beam_bending_static_stvk.py", line 135, in <module>
    main()
  File "febio_rectangular_beam_bending_static_stvk.py", line 116, in main
    elements = sort_elements(meshio_to_febio_element_types, parameters)
  File "/home/arnaud/dev/caribou/Validation/fenics/febio validation/febio_scene.py", line 161, in sort_elements
    type, indices = block
```
For NumPy, I am on v 1.22.3 and meshio v 5.3.4.
Check the compatibility with previous NumPy version (that is my principal suspect)

**Comment by Sidaty1** [comment]
The function `sort_elements` seems to not be compatible with the latest version of meshio( Meshio 5.3.4), for the moment we are able to work with meshio5.0.4  to move forward with other more important issues and we will handle this compatibility problem later.
